"""add device_family to devices

Revision ID: 57c406d6595e
Revises: ddf6b4ebd20d
Create Date: 2026-09-27 11:19:32.657928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c406d6595e'
down_revision: Union[str, Sequence[str], None] = 'ddf6b4ebd20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default=sa.text("'sensor'"), nullable=False))
    op.create_index('ix_devices_device_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_device_family', table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###
