"""devices

Revision ID: ddf6b4ebd20d
Revises: 4b533c891988
Create Date: 2026-09-15 20:38:58.037676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf6b4ebd20d'
down_revision: Union[str, Sequence[str], None] = '4b533c891988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'sensor'"), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_role', 'devices', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_role', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
